name: build
env:
  version: '0.1.16'

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Install requirements
        run: |
          sudo apt-get install -y --no-install-recommends \
            apt-utils \
            automake \
            build-essential \
            ca-certificates \
            cmake \
            debconf \
            debhelper \
            dpkg \
            gnupg \
            pkg-config \
            software-properties-common
      - name: Prepare template
        run: |
          mkdir -p td-libnice-dev_${{env.version}}
          cp -rv DEBIAN.template td-libnice-dev_${{env.version}}/DEBIAN
          sed -i "s/%VERSION%/${{env.version}}/g" td-libnice-dev_${{env.version}}/DEBIAN/*
      - name: Download lib
        run: |
          mkdir -p td-libnice-dev_${{env.version}}/usr/local/src
          cd td-libnice-dev_${{env.version}}/usr/local/src
          curl -L -o libnice-${{env.version}}.tar.gz https://github.com/libnice/libnice/archive/${{env.version}}.tar.gz
          tar zvxf libnice-${{env.version}}.tar.gz
          rm libnice-${{env.version}}.tar.gz
      - name: Build .deb
        run: |
          dpkg-deb --build td-libnice-dev_${{env.version}}
          mkdir -p dist
          mv td-libnice-dev_${{env.version}}.deb dist
          ls -lah dist
      - name: Try install
        working-directory: dist
        run: |
          sudo dpkg -i td-libnice-dev_${{env.version}}.deb
      - name: Install SSH Client
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          REPOSITORY_NAME: tada-team/tada-team.github.io
          TARGET_FOLDER: td-libnice-dev-dist
          FOLDER: dist
          SSH: true
          BRANCH: main
